# Generated by Django 5.0.3 on 2024-03-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_description', models.TextField(unique=True, verbose_name='Question description')),
                ('correct_answer', models.CharField(max_length=50, verbose_name='Correct_Answer')),
                ('wrong_answer1', models.CharField(max_length=50, verbose_name='Wrong Answer 1')),
                ('wrong_answer2', models.CharField(blank=True, max_length=50, verbose_name='Wrong Answer 2')),
                ('wrong_answer3', models.CharField(blank=True, max_length=50, verbose_name='Wrong Answer 3')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
