name: CI workflow

on: push

env:
  PYTHON_VERSION: '3.11'
  POETRY_VERSION: '1.7.1'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'
          cache-dependency-path: poetry.lock
      - name: Set Poetry environment
        run: |
          poetry env use ${{ env.PYTHON_VERSION }}
          - name: Install dependencies
            run: |
              poetry lock --no-update
              poetry install --no-root
